"""Add votes column to comments table

Revision ID: 3fcb1f0900c3
Revises: 12f964b7b964
Create Date: 2023-04-08 21:03:08.721122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcb1f0900c3'
down_revision = '12f964b7b964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
