"""Add avatar data to user table

Revision ID: 82e1e11fdf8d
Revises: 3fcb1f0900c3
Create Date: 2023-04-09 11:16:20.965589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e1e11fdf8d'
down_revision = '3fcb1f0900c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backdrop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clothingData', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eyeStyle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hairColor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('skinColor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('skinColor')
        batch_op.drop_column('hairColor')
        batch_op.drop_column('eyeStyle')
        batch_op.drop_column('clothingData')
        batch_op.drop_column('backdrop')

    # ### end Alembic commands ###
