"""district table added

Revision ID: c62072892627
Revises: d378f124db50
Create Date: 2023-04-13 17:02:18.596806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62072892627'
down_revision = 'd378f124db50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_districts_post_id_posts', type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_district_id_districts'), 'districts', ['district_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_district_id_districts'), type_='foreignkey')
        batch_op.drop_column('district_id')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_districts_post_id_posts', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
