"""updated upvotes/downvotes to just votes

Revision ID: d619b8287fe8
Revises: c2e9c81d9d63
Create Date: 2023-04-06 20:19:10.422756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd619b8287fe8'
down_revision = 'c2e9c81d9d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('downvotes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
